development:
  clients:
    default:
      database: marcus_pereira_blog_dev
      hosts:
        - localhost:27017
testing:
  clients:
    default:
      database: marcus_pereira_blog_test
      hosts:
        - localhost:27017